spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csmall_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false

#配置seata
seata:
  tx-service-group: csmall_group  #定义一个事务分组名称，一般是为了区分项目
  service:
    vgroup-mapping:
      csmall_group: default #csmall_group组使用默认的seata配置完成事务
    grouplist:
      default: localhost:8091 #设置Seata所在的地址(默认端口号就是8091)
