spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/csmall_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
  #    username: root
  #    password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 00879d96-7a8f-4c99-8dbd-25903ace45d2    #命名空间ID

#配置dubbo相关信息
dubbo:
  protocol:
    #port设置为-1，是Dubbo的特殊写法
    #每一个服务使用dubbo时，都需要一个端口启动dubbo，默认是20880开始的
    #设置成-1，会自动分配端口号，从20880开始分配，如果被占用就递增
    port: -1
    #设置连接名称，一般固定叫dubbo
    name: dubbo
  registry:
    #声明注册中心的类型和地址
    address: nacos://localhost:8848
  #    parameters[namespace]: 00879d96-7a8f-4c99-8dbd-25903ace45d2
  #当项目启动时，作为消费者，是否要检查所有远程服务可用，false表示不检查
  consumer:
    check: false

#配置seata
seata:
  tx-service-group: csmall_group  #定义一个事务分组名称，一般是为了区分项目
  service:
    vgroup-mapping:
      csmall_group: default #csmall_group组使用默认的seata配置完成事务
    grouplist:
      default: localhost:8091 #设置Seata所在的地址(默认端口号就是8091)
